name: tap_{{ cookiecutter.data_source_name }}
version: "0.1.0"
require-dbt-version: [">=0.20.0", "<=1.0.0"]

config-version: 2
profile: local

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  tap_{{ cookiecutter.data_source_name }}:
    base:
      +materialized: table

vars:
  schema: {% raw %}"{{ env_var('DBT_TARGET_SCHEMA') }}"{% endraw %}
